USE [master]
GO

/****** Object:  Database [AGH-Hurtownie_Danych]    Script Date: 23.03.2017 22:40:59 ******/
CREATE DATABASE [AGH-Hurtownie_Danych]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AGH-Hurtownie_Danych', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\AGH-Hurtownie_Danych.mdf' , SIZE = 9216KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AGH-Hurtownie_Danych_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\AGH-Hurtownie_Danych_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AGH-Hurtownie_Danych].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET ARITHABORT OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET  MULTI_USER 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AGH-Hurtownie_Danych] SET  READ_WRITE 
GO

